name: habit_tracker_flutter
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_action_sheet: 2.0.0
  cupertino_icons: 1.0.2
  flutter_launcher_icons: 0.9.0
  flutter_riverpod: 1.0.0-dev.6
  flutter_svg: 0.22.0
  hive: 2.0.4
  hive_flutter: 1.0.0
  modal_bottom_sheet: 2.0.0
  page_flip_builder: 0.1.3
  uuid: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.0.1
  hive_generator: 1.1.0

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon.png"




flutter:

  
  
  
  uses-material-design: true
  
  assets:
    - assets/
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
